In [50]:
import torch
import numpy as np
import pandas as pd
import os

os.chdir("../")

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [51]:
from pathlib import Path

data_root = Path(os.getenv("PASTIS_DATA_DIR", "")) # Path to PASTIS data directory
assert data_root.is_dir(), f"PASTIS data directory not found at {data_root}"

In [ ]:
from src.data.components.pastis import PASTISSubpatchedDatasetS2

dataset = PASTISSubpatchedDatasetS2(data_root, 3, with_datetime=True)
len(dataset)

37411

In [65]:
from src.data.transforms import TemporalFeatureExtraction

temp = TemporalFeatureExtraction()

In [72]:
import pandas as pd

sample = dataset[0]
temp.transform(sample["dates"])

[267 272 277] 3


array([[267],
       [272],
       [277]], dtype=int32)

In [35]:
from src.data.base_datamodule import BaseDataModule

base = BaseDataModule(train=dataset, batch_size=16)
base

In [38]:
base.setup("train")

In [39]:
bx = base.train_dataloader()
bx

In [42]:
data = next(iter(bx))
data["dates"]

tensor([[20180924, 20180929, 20181123, 20190117, 20190122, 20190216, 20190221,
         20190226, 20190313, 20190328, 20190412, 20190422, 20181004, 20190427,
         20190512, 20190527, 20190601, 20190606, 20190621, 20190626, 20190701,
         20190706, 20190711, 20181009, 20190716, 20190731, 20190810, 20190815,
         20190820, 20190825, 20190830, 20190904, 20190914, 20190919, 20181019,
         20190924, 20191009, 20191019, 20181024, 20181029, 20181108, 20181113,
         20181118],
        [20180924, 20180929, 20181123, 20190117, 20190122, 20190216, 20190221,
         20190226, 20190313, 20190328, 20190412, 20190422, 20181004, 20190427,
         20190512, 20190527, 20190601, 20190606, 20190621, 20190626, 20190701,
         20190706, 20190711, 20181009, 20190716, 20190731, 20190810, 20190815,
         20190820, 20190825, 20190830, 20190904, 20190914, 20190919, 20181019,
         20190924, 20191009, 20191019, 20181024, 20181029, 20181108, 20181113,
         20181118],
        [201